- hosts: "{{ hosts }}"
  become: true
  
    - name: Download and install ElasticSearch
      shell: 'wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -'

    - name: Add elastic source to source.list.d directory
      shell: 'echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list'

    - name: update and Install ElasticSearch
      apt:
        name: "{{ item }}"
        state: present
        with_items:
          - default-jre 
          - elasticsearch
          - kibana

    - name: Configure ElasticSearch
      lineinfile:
        path: "/etc/elasticsearch/elasticsearch.yml"
        regexp: '^network.host'
        line: 'network.host: localhost'

    - name: Configure Java
      lineinfile:
        path: "/etc/elasticsearch/vm.options"
        regexp: "{{ item.size }}"
        line: "{{ item.value }}"
        with_items:
          - { size: -Xms1g, value: -Xms200m }
          - { size: -Xmx1g, value: -Xmx200m }

    - name: Enable Security Setting in ElasticSearch
      lineinfile:
        path: "/etc/elasticsearch/elasticsearch.yml"
        line: 'xpack.security.enabled: true'

    - name: Configure username and password for ElasticSearch
      shell: curl -XPUT -u elastic:changeme 'localhost:9200/_xpack/security/user/elastic/_password?pretty' 

    - name: Start ElasticSearch
      systemd:
        state: restarted
        name: elasticsearch
